on: [push]

jobs:
  update_version_job:
    runs-on: ubuntu-latest
    name: A job to update the version inside the api.yml file on release
    steps:
    - uses: actions/checkout@v2
    - name: Updates the version
      id: update
      uses: FranKrow/js-action@v2.1
      with:
        files: 'package.json, api.yaml'
        version-regexp: '\d+.\d+.\d+'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    # Use the output from the `update` step
    - name: Get the output time
      run: echo "The time was ${{ steps.update.outputs.time }}"